# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host:
  port: 1883
  ssl: false
  username:
  password:

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

# Floors w/ the points to draw it in meters
floors:
  - id: first
    name: First Floor
  # Bounds (x,y,z) of map in  meters
    bounds: [[-1, -1, 0], [18, 20, 3.1]]
    rooms:
      - name: Powder
        points:
          - [6.2, 11]
          - [8, 11]
          - [8, 9]
          - [6.2, 9]
          - [6.2, 11]
      - name: Office
        points:
          - [6.2, 14.5]
          - [9.6, 14.5]
          - [9.6, 12.5]
          - [8.6, 11]
          - [6.2, 11]
          - [6.2, 14.5]
      - name: Family
        points:
          - [0, 0]
          - [0, 5.5]
          - [5.2, 5.5]
          - [5.2, 0]
          - [0, 0]
      - name: Kitchen
        points:
          - [5.6, 2]
          - [5.6, 8.5]
          - [12.5, 8.5]
          - [12.5, 2]
          - [5.6, 2]
      - name: Garage
        points:
          - [0, 19.2]
          - [6.1, 19.2]
          - [6.1, 9]
          - [0, 9]
          - [0, 19.2]
      - name: Living
        points:
          - [16.6, 13.25]
          - [16.6, 7.75]
          - [12.6, 7.75]
          - [12.6, 13.25]
          - [16.6, 13.25]
      - name: Dining
        points:
          - [16.6, 2]
          - [16.6, 7.75]
          - [15.4, 7.75]
          - [12.6, 7.75]
          - [12.6, 2]
          - [16.6, 2]
      - name: Foyer
        points:
          - [9.6, 13.25]
          - [12.5, 13.25]
          - [12.5, 10]
          - [9.6, 10]
          - [9.6, 13.25]
      - name: Laundry
        points:
          - [0, 8.85]
          - [4.5, 8.85]
          - [4.5, 5.65]
          - [0, 5.65]
          - [0, 8.85]
  - id: second
    name: Second Floor
    bounds: [[-1, -1, 3.1], [18, 20, 6.2]]
  - id: outside
    name: Outside
    bounds: [[-10, -10, 0], [28, 30, 20]]

# Locations of espresense nodes in meters
nodes:
  - name: Master
    point: [4, 13, 4.2]
    floors: ["second"]
  - name: Bathroom
    point: [0.1, 10, 4.2]
    floors: ["second"]
  - name: Garage
    point: [1, 19, 0.5]
    floors: ["first"]
  - name: Office
    point: [7, 13.25, 0.5]
    floors: ["first"]
  - name: Office 2
    point: [7, 11, 0.25]
    floors: ["first"]
  - name: Family
    point: [0.5, 0.5, 0.25]
    floors: ["first"]
  - name: Kitchen
    point: [8, 7.5, 0.5]
    floors: ["first"]
  - name: Dining
    point: [16.4, 2.3, 0.5]
    floors: ["first"]
  - name: Basement
    point: [16.2, 13.1, -1.5]
    floors: ["first"]
  - name: Laundry
    point: [5, 9, 2]
    floors: ["first"]
  - name: VW EOS
    point: [0, 0, 0]
    floors: ["outside"]
# Devices to track
devices:
  - name: Darrell Watch
    id: darrells-watch
